apiVersion: v1
kind: Service
metadata:
  name: stewart-nodeport-service
  namespace: stewart-eks-activity
spec:
  type: NodePort
  selector:
    app: httpd-app
  ports:
    - protocol: TCP
      port: 30001
      targetPort: 5678
