#  3. Secret – Storing sensitive data (base64 encoded)
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: dXNlcg==        # echo -n 'user' | base64
  password: cGFzc3dvcmQ=    # echo -n 'password' | base64
